title: Python Codes from Murilo Arguello
author: Murilo Arguello
email: muriloarguello@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Murilo Arguello's blog related to python programming. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  muriloarguello # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
